version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: wolmanager-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  wolmanager:
    build: .
    container_name: wolmanager-app
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - NETWORK_RANGE=192.168.1.0/24
      - DISCOVERY_INTERVAL=300
      - DISCOVERY_EARLY_TERMINATION=true
      - DISCOVERY_MIN_HOSTS_THRESHOLD=5
      - WOL_BROADCAST_ADDRESS=192.168.1.255
      - DEBUG=false
    volumes:
      - ./env.example:/app/.env:ro
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    network_mode: host

volumes:
  redis_data:


